lib/shorty_web/router.ex
defmodule ShortyWeb.Router do
  use ShortyWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ShortyWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/urls", UrlController
    get "/r/:token", UrlController, :redir
  end

  # Other scopes may use custom stacks.
  # scope "/api", ShortyWeb do
  #   pipe_through :api
  # end
end

lib/shorty/application.ex
defmodule Shorty.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      Shorty.Repo,
      # Start the endpoint when the application starts
      ShortyWeb.Endpoint
      # Starts a worker by calling: Shorty.Worker.start_link(arg)
      # {Shorty.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Shorty.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    ShortyWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/shorty/repo.ex
defmodule Shorty.Repo do
  use Ecto.Repo,
    otp_app: :shorty,
    adapter: Ecto.Adapters.Postgres
end

lib/shorty/urls.ex
defmodule Shorty.Urls do
  @moduledoc """
  The Urls context.
  """

  import Ecto.Query, warn: false
  alias Shorty.Repo

  alias Shorty.Urls.Url

  @doc """
  Returns the list of urls.

  ## Examples

      iex> list_urls()
      [%Url{}, ...]

  """
  def list_urls do
    Repo.all(Url)
  end

  @doc """
  Gets a single url.

  Raises `Ecto.NoResultsError` if the Url does not exist.

  ## Examples

      iex> get_url!(123)
      %Url{}

      iex> get_url!(456)
      ** (Ecto.NoResultsError)

  """
  def get_url!(id), do: Repo.get!(Url, id)

  defp random_token(length \\ 5) do
    :crypto.strong_rand_bytes(length)
    |> Base.url_encode64
    |> binary_part(0, length)
  end

  @doc """
  Creates a url.

  ## Examples

      iex> create_url(%{field: value})
      {:ok, %Url{}}

      iex> create_url(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_url(attrs \\ %{}) do
    attrs = Map.put(attrs, "token", random_token())

    %Url{}
    |> Url.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a url.

  ## Examples

      iex> update_url(url, %{field: new_value})
      {:ok, %Url{}}

      iex> update_url(url, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_url(%Url{} = url, attrs) do
    url
    |> Url.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Url.

  ## Examples

      iex> delete_url(url)
      {:ok, %Url{}}

      iex> delete_url(url)
      {:error, %Ecto.Changeset{}}

  """
  def delete_url(%Url{} = url) do
    Repo.delete(url)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking url changes.

  ## Examples

      iex> change_url(url)
      %Ecto.Changeset{source: %Url{}}

  """
  def change_url(%Url{} = url) do
    Url.changeset(url, %{})
  end

  @doc """
  Gets a Url for a token, or nil if none found
  """
  def get_by_token(token) do
    from(u in Url, where: u.token == ^token)
    |> Repo.one
  end
end

lib/shorty/urls/url.ex
defmodule Shorty.Urls.Url do
  use Ecto.Schema
  import Ecto.Changeset


  schema "urls" do
    field :token, :string
    field :url, :string

    timestamps()
  end

  @doc false
  def changeset(url, attrs) do
    url
    |> cast(attrs, [:token, :url])
    |> validate_required([:token, :url])
    |> validate_format(:url, ~r(^https?://), message: "Must be fully qualified domain name")
  end
end

lib/shorty_web/controllers/page_controller.ex
defmodule ShortyWeb.PageController do
  use ShortyWeb, :controller

  def index(conn, _params) do
    redirect(conn, to: Routes.url_path(conn, :index))
  end
end

lib/shorty_web/controllers/url_controller.ex
defmodule ShortyWeb.UrlController do
  use ShortyWeb, :controller

  alias Shorty.Urls
  alias Shorty.Urls.Url

  def index(conn, _params) do
    urls = Urls.list_urls()
    render(conn, "index.html", urls: urls)
  end

  def new(conn, _params) do
    changeset = Urls.change_url(%Url{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"url" => url_params}) do
    case Urls.create_url(url_params) do
      {:ok, url} ->
        conn
        |> put_flash(:info, "Url created successfully.")
        |> redirect(to: Routes.url_path(conn, :show, url))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    url = Urls.get_url!(id)
    render(conn, "show.html", url: url)
  end

  def edit(conn, %{"id" => id}) do
    url = Urls.get_url!(id)
    changeset = Urls.change_url(url)
    render(conn, "edit.html", url: url, changeset: changeset)
  end

  def update(conn, %{"id" => id, "url" => url_params}) do
    url = Urls.get_url!(id)

    case Urls.update_url(url, url_params) do
      {:ok, url} ->
        conn
        |> put_flash(:info, "Url updated successfully.")
        |> redirect(to: Routes.url_path(conn, :show, url))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", url: url, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    url = Urls.get_url!(id)
    {:ok, _url} = Urls.delete_url(url)

    conn
    |> put_flash(:info, "Url deleted successfully.")
    |> redirect(to: Routes.url_path(conn, :index))
  end

  def redir(conn, %{"token" => token}) do
    case Urls.get_by_token(token) do
      nil ->
        conn
        |> put_flash(:error, "Invalid Url")
        |> redirect(to: Routes.url_path(conn, :index))

      url ->
        redirect(conn, external: url.url)
    end
  end
end

lib/shorty_web/views/error_view.ex
defmodule ShortyWeb.ErrorView do
  use ShortyWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/shorty_web/views/layout_view.ex
defmodule ShortyWeb.LayoutView do
  use ShortyWeb, :view
end

lib/shorty_web/views/page_view.ex
defmodule ShortyWeb.PageView do
  use ShortyWeb, :view
end

lib/shorty_web/views/url_view.ex
defmodule ShortyWeb.UrlView do
  use ShortyWeb, :view

  @doc """
  Create a link who's text is the same as the link target
  """
  def link_and_text(str) do
    link(str, to: str)
  end
end

lib/shorty_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Shorty · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
          </ul>
        </nav>
        <a href="http://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/shorty_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>A productive web framework that<br/>does not compromise speed and maintainability.</p>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.4/CHANGELOG.md">v1.4 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on Freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
    </ul>
  </article>
</section>

lib/shorty_web/templates/url/edit.html.eex
<h1>Edit Url</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.url_path(@conn, :update, @url)) %>

<span><%= link "Back", to: Routes.url_path(@conn, :index) %></span>

lib/shorty_web/templates/url/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :url %>
  <%= text_input f, :url %>
  <%= error_tag f, :url %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/shorty_web/templates/url/index.html.eex
<h1>Listing Urls</h1>

<table>
  <thead>
    <tr>
      <th>Token</th>
      <th>Url</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for url <- @urls do %>
    <tr>
      <td><%= url.token %></td>
      <td><%= url.url %></td>

      <td>
        <%= link "Show", to: Routes.url_path(@conn, :show, url) %>
        <%= link "Edit", to: Routes.url_path(@conn, :edit, url) %>
        <%= link "Delete", to: Routes.url_path(@conn, :delete, url), method: :delete, data: [confirm: "Are you sure?"] %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Url", to: Routes.url_path(@conn, :new) %></span>

lib/shorty_web/templates/url/new.html.eex
<h1>New Url</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.url_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.url_path(@conn, :index) %></span>

lib/shorty_web/templates/url/show.html.eex
<h1>Show Url</h1>

<ul>

  <li>
    <strong>Token:</strong>
    <%= @url.token %>
  </li>

  <li>
    <strong>Url:</strong>
    <%= link_and_text @url.url %>
  </li>

  <li>
    <strong>Link:</strong>
    <%= link_and_text Routes.url_url(@conn, :redir, @url.token) %>
  </li>
</ul>

<span><%= link "Edit", to: Routes.url_path(@conn, :edit, @url) %></span>
<span><%= link "Back", to: Routes.url_path(@conn, :index) %></span>